language: python
python:
  #- 2.6
  #- 2.7
  #- 3.2
  #- 3.3
  #- 3.4
  - 3.5
  - 3.6
#before_script:
#  - "export DISPLAY=:99.0"
#  - "sh -e /etc/init.d/xvfb start"
#  - sleep 3 # give xvfb some time to start
#env:
#  - MOZ_HEADLESS=1
sudo: required
addons:
  chrome: stable
  #firefox: latest
install: pip install -r requirements.txt
script:
    - ./run.py
